blog/urls.py
from django.urls import path

from blog.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, BlogpostDeleteView

app_name = 'blog'


urlpatterns = [
     path('', BlogpostListView.as_view(), name='blog_list'),
     path('view/<int:pk>/', BlogpostDetailView.as_view(), name='view'),
     path('create/', BlogpostCreateView.as_view(), name='create'),
     path('update/<int:pk>/', BlogpostUpdateView.as_view(), name='update'),
     path('delete/<int:pk>/', BlogpostDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='Blogpost/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    publication_sign = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = ("Запись")
        verbose_name_plural = ("Записи")

blog/views.py
from django.urls import reverse_lazy
from pytils.translit import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blogpost


class BlogpostCreateView(CreateView):
    model = Blogpost
    fields = ('title', 'content', 'publication_sign', 'preview')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
        return super().form_valid(form)


class BlogpostListView(ListView):
    model = Blogpost

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication_sign=True)
        return queryset


class BlogpostDetailView(DetailView):
    model = Blogpost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogpostUpdateView(UpdateView):
    model = Blogpost
    fields = ('title', 'content', 'publication_sign', 'preview')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
        return super().form_valid(form)

    def get_success_url(self):
        from django.urls import reverse
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogpostDeleteView(DeleteView):
    model = Blogpost
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить статью: "{{ object.title | truncatechars:40 }}"? </p>
                        <button Type="submit" class="btn btn-danger"> Подтвердить </button>
                        <a Type="submit" href="{% url 'blog:blog_list' %}" class="btn btn-success">
                            Вернуться назад </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'catalog/base.html' %}
{% load tag %}

{% block content %}


<h1 align="center"> {{ object|title }} ( {{ object.slug }} ) </h1>

<div class="card px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="width: 24rem;">
  <div class="card-body">
    <img class="card-img-top" src="{{ object.preview | media }}">
    <p class="card-text"> {{ object.content }}</p>
    <p class="card-text">{{ object.created_at }}</p>
    <p class="card-text"> Просмотров: {{ object.view_count }}</p>
    <div class="d-grid gap-2 mx-auto">
    <a href="{% url 'blog:blog_list' %}" class="w-100 btn btn-lg btn-outline-warning"> Назад </a>
    </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button Type="submit" class="btn btn-success">
                            {% if object %}
                            Изменить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'catalog/base.html' %}

{% block title %} Новостной блог {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"><font color="green"><strong> Новостной блог </strong></font></h1>
</div>
<div class="col-12 mb-5 text-center">
    <a class="btn btn-outline-success" href="{% url 'blog:create' %}"> Добавить статью </a>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}

        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 align="center" class="my-0 fw-normal"><strong>{{ object|title | truncatechars:40 }} </strong>
                    </h4>
                </div>
                <div class="card-body">
                    <ul align="center" class="list-unstyled mt-3 mb-4">
                        <li>{{ object.content | truncatechars:100 }}</li>
                        <li>{{ object.created_at }}</li>
                        <li>Просмотров: {{ object.view_count }}</li>
                    </ul>
                    <a href="{% url 'blog:view' object.pk %}" class="w-100 btn btn-lg btn-outline-success">
                        Подробнее </a>
                    <a href="{% url 'blog:update' object.pk %}" class="w-100 btn btn-lg btn-outline-success">
                        Редактировать новость </a>
                    <a href="{% url 'blog:delete' object.pk %}" class="w-100 btn btn-lg btn-outline-danger"> Удалить
                        новость </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>