blog/urls.py
from django.urls import path

from blog.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, BlogpostDeleteView

app_name = 'blog'


urlpatterns = [
     path('', BlogpostListView.as_view(), name='blog_list'),
     path('view/<int:pk>/', BlogpostDetailView.as_view(), name='view'),
     path('create/', BlogpostCreateView.as_view(), name='create'),
     path('update/<int:pk>/', BlogpostUpdateView.as_view(), name='update'),
     path('delete/<int:pk>/', BlogpostDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path

from catalog.views import ProductListView, ProductDetailView, ProductView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = 'shop'
urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ProductView.as_view(), name='contacts'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='Наименование категории')
    category_description = models.TextField(max_length=200, verbose_name='Описание категории')

    def __str__(self):
        return f'{self.category_name} {self.category_description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    product_name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(max_length=300, verbose_name='Описание')
    preview = models.ImageField(upload_to='preview/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.product_name} {self.description}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Version(models.Model):

    number_version = models.IntegerField(default=1, verbose_name="Номер версии")
    name = models.CharField(max_length=100, verbose_name='Название версии')
    is_active = models.BooleanField(default=False, verbose_name='Активная версия')
    product = models.ForeignKey("Product", on_delete=models.CASCADE, verbose_name='Продукт')

    def __str__(self):
        return f'{self.number_version}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from django.forms.fields import BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    # Наследуемся от специального класса форм, который предоставляет
    # весь необходимый функционал, который нужно настроить
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', )

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('product_name')
        words_exception = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in words_exception:
            if word in cleaned_data:
                raise forms.ValidationError('Ошибка в названии товара')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        words_exception = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in words_exception:
            if word in cleaned_data:
                raise forms.ValidationError('Ошибка в описании')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.models import Product, Version
from django.forms import inlineformset_factory
from catalog.forms import ProductForm, VersionForm


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = Product.objects.all()

        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(is_active=True)
            if active_versions:
                product.active_version = active_versions.last().name
            else:
                product.active_version = 'Нет активной версии'

        context_data['object_list'] = products
        return context_data


class ProductView(View):
    def get(self, request):
        return render(request, 'catalog/contacts.html')

    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Name: {name}, Phone: {phone}, Message: {message}')
        return render(request, 'catalog/contacts.html')


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product = self.get_object()
        versions = Version.objects.filter(product=product)
        active_version = versions.filter(is_active=True).last()

        if active_version:
            product.active_version = active_version.name
        else:
            product.active_version = 'Нет активной версии'

        context_data['object'] = product
        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:product_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shop:product_list')

catalog/templates/catalog/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% block menu %}

{% include 'catalog/menu.html' %}

{% endblock %}

{% block content %}
{% endblock %}

</body>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Продукты для всех
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}


{% block title %} Контакты {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>45-1148942</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Краснодар,КРД,54052-6119</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/menu.html
{% block menu %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Продукты для всех</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
    </nav>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить товар: "{{ object.product_name }}" ? </p>
                        <button Type="submit" class="btn btn-success"> Подтвердить </button>
                    </form>
                    <a href="{% url 'shop:product_list' %}" class="btn btn-success" style="margin-top: 10px;"> Вернуться назад </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load tag %}
{% block title %} Инфо {% endblock %}

{% block content %}


<h1 align="center"> {{ object|title }} </h1>

<div class="card px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="width: 24rem;">
    <div class="card-body">
        <img class="good_logo" src="{{ object.preview| media }}" width="300" height="300">
        <h5 class="card-title">{{ object.nomination | upper}}</h5>
        <p class="card-text">Описание: {{ object.description }}</p>
        <p class="card-text">Категория: {{ object.category }}</p>
        <p class="card-text">Дата создания: {{ object.created_at }}</p>
        <p class="card-text">Дата последнего изменения: {{ object.updated_at }}</p>
        <p class="card-text">Активная версия: {{ object.active_version }}</p>
        <div class="d-grid gap-2 mx-auto">
            <a href="#" class="btn btn-success"> Стоимость {{object.price | floatformat:'2'}} руб</a>
            <a href="{% url 'shop:product_list' %}" class="w-100 btn btn-lg btn-outline-warning"> Назад </a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <h3> Редактировать товар </h3>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button Type="submit" class="btn btn-success">
                        {% if object %}
                        Изменить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <h3> Версии товара </h3>
            <div class="card">
                <div class="card-body">
                    {{formset.management_form }}
                    {% for form in formset.forms %}
                    {{form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block title %} Главная {% endblock %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Продукты для всех</h1>
    <p class="lead"> Продуктовый онлайн-магазин </p>
</div>
<div class="col-12 mb-5 text-center">
    <a class="w-100 btn btn-lg btn-outline-primary" href="{% url 'shop:product_create' %}"> Добавить товар </a>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}

        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 align="center" class="my-0 fw-normal">{{ object|title }}</h4>
                </div>
                <div class="card-body">
                    <h1 align="center" class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    <ul align="center" class="list-unstyled mt-3 mb-4">
                        <li>{{ object.category }}</li>
                        <li>{{ object.description | truncatechars:100 }}</li>
                        <li> Активная версия: {{ object.active_version }}</li>
                    </ul>
                    <a href="{% url 'shop:product_detail' object.pk %}" class="w-100 btn btn-lg btn-outline-primary"> О товаре </a>
                    <a href="{% url 'shop:product_update' object.pk %}" class="w-100 btn btn-lg btn-outline-primary"> Редактировать товар </a>
                    <a href="{% url 'shop:product_delete' object.pk %}" class="w-100 btn btn-lg btn-outline-primary"> Удалить товар </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}